packages:
  - 'packages/**'
  - 'apps/**'

catalogs:
  vue3.4:
    vue: ^3.5.11
    'vue-router': ^4.3.3
    pinia: ^2.1.7
    pinia-plugin-persistedstate: ^4.1.1
    '@vueuse/core': "^11.1.0"
  vite5:
    vite: ^5.4.8
    vite-plugin-compression: ^0.5.1
    vite-plugin-mock: ^3.0.2
    '@vitejs/plugin-vue': ^5.0.5
    '@vitejs/plugin-vue-jsx': ^4.0.0
    vite-plugin-vue-devtools: ^7.3.1
    vitest: ^1.6.0
    '@playwright/test': ^1.44.1
    'eslint-plugin-playwright': ^1.6.2
